//LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//LOGOUT
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

//USER LOADING
export const USER_LOADING_REQUEST = 'USER_LOADING_REQUEST';
export const USER_LOADING_SUCCESS = 'USER_LOADING_SUCCESS';
export const USER_LOADING_FAILURE = 'USER_LOADING_FAILURE';

//CLEAR ERROR
export const CLEAR_ERROR_REQUEST = 'CLEAR_ERROR_REQUEST';
export const CLEAR_ERROR_SUCCESS = 'CLEAR_ERROR_SUCCESS';
export const CLEAR_ERROR_FAILURE = 'CLEAR_ERROR_FAILURE';

//REGISTER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// POST LOADING
export const POSTS_LOADING_REQUEST = 'POST_LOADING_REQUEST';
export const POSTS_LOADING_FAILURE = 'POST_LOADING_FAILURE';
export const POSTS_LOADING_SUCCESS = 'POST_LOADING_SUCCESS';

// //POST UPLOAD
export const POST_UPLOAD_REQUEST = 'POST_UPLOAD_REQUEST';
export const POST_UPLOAD_SUCCESS = 'POST_UPLOAD_SUCCESS';
export const POST_UPLOAD_FAILURE = 'POST_UPLOAD_FAILURE';

//POST DETAIL LOADING
export const POST_DETAIL_LOADING_REQUEST = 'POST_DETAIL_LOADING_REQUEST';
export const POST_DETAIL_LOADING_SUCCESS = 'POST_DETAIL_LOADING_SUCCESS';
export const POST_DETAIL_LOADING_FAILURE = 'POST_DETAIL_LOADING_FAILURE';

//POST DELETE
export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAILURE = 'POST_DELETE_FAILURE';

// Post EDIT LOADING
export const POST_EDIT_LOADING_REQUEST = 'POST_EDIT_LOADING_REQUEST';
export const POST_EDIT_LOADING_FAILURE = 'POST_EDIT_LOADING_FAILURE';
export const POST_EDIT_LOADING_SUCCESS = 'POST_EDIT_LOADING_SUCCESS';

// Post EDIT UPLOAD
export const POST_EDIT_UPLOAD_REQUEST = 'POST_EDIT_UPLOAD_REQUEST';
export const POST_EDIT_UPLOAD_FAILURE = 'POST_EDIT_UPLOAD_FAILURE';
export const POST_EDIT_UPLOAD_SUCCESS = 'POST_EDIT_UPLOAD_SUCCESS';

//COMMENT LOADING
export const COMMENT_LOADING_REQUEST = 'COMMENT_LOADING_REQUEST';
export const COMMENT_LOADING_SUCCESS = 'COMMENT_LOADING_SUCCESS';
export const COMMENT_LOADING_FAILURE = 'COMMENT_LOADING_FAILURE';

//COMMENT UPLOAD
export const COMMENT_UPLOAD_REQUEST = 'COMMENT_UPLOAD_REQUEST';
export const COMMENT_UPLOAD_SUCCESS = 'COMMENT_UPLOAD_SUCCESS';
export const COMMENT_UPLOAD_FAILURE = 'COMMENT_UPLOAD_FAILURE';

// CATEGORY FIND
export const CATEGORY_FIND_REQUEST = 'CATEGORY_FIND_REQUEST';
export const CATEGORY_FIND_FAILURE = 'CATEGORY_FIND_FAILURE';
export const CATEGORY_FIND_SUCCESS = 'CATEGORY_FIND_SUCCESS';

// POST SEARCH
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';

// PASSWORD EDIT
export const PASSWORD_EDIT_UPLOAD_REQUEST = 'PASSWORD_EDIT_UPLOAD_REQUEST';
export const PASSWORD_EDIT_UPLOAD_FAILURE = 'PASSWORD_EDIT_UPLOAD_FAILURE';
export const PASSWORD_EDIT_UPLOAD_SUCCESS = 'PASSWORD_EDIT_UPLOAD_SUCCESS';
